### ISSUE TITLE
jQuery noConflict Issue

### ISSUE THREAD

**Issue by srikat** [jjcosgrove/jquery-aniview#1]
I integrated this in a WordPress site and realized that Aniview will not work unless

`!function()`

is changed to

`!function($)`

near the beginning

and

`()`

is changed to

`(jQuery)`

near the end in jquery.aniview.min.js.

This is most probably because the jQuery library included with WordPress is set to the noConflict() mode per https://codex.wordpress.org/Function_Reference/wp_enqueue_script#jQuery_noConflict_Wrappers.

You might want to make this change in jquery.aniview.js and jquery.aniview.min.js if necessary.

**Comment by codebard** [comment]
I second this. The lib does not work with WordPress unless you do the change srikat explained. That should be fixed.
