### ISSUE TITLE
Remove div.av-container / Destroys layout

### ISSUE THREAD

**Issue by godsdog** [jjcosgrove/jquery-aniview#14]
Can you add the feature to disable the output of the outer div : `<div class="av-container av-visible"> ... </div>`

I use a complex layout and this div destroys my layout, because I use absolute positioning in child divs.

Furthermore the `:nth-child(n)` selector on my original layout is not working anymore.

**Comment by godsdog** [comment]
Quick fix: `.av-container {position: static;}` for the positioning issue.

**Comment by godsdog** [comment]
Just fixed it on my self:
L:26 `        var settings = $.extend({
            animateThreshold: 0,
            scrollPollInterval: 20,
			showWrapper: false
        }, options);`
L:39 `if (settings.showWrapper) {$(element).wrap('<div class="av-container"></div>');}`
L:63: `               if (settings.showWrapper) {
				   	var elementParentContainer = $(element).parent('.av-container');
			   } else {
				   	var elementParentContainer = $(element);
			   }`

**Comment by suetorres** [comment]
> Just fixed it on my self:
> L:26 ` var settings = $.extend({ animateThreshold: 0, scrollPollInterval: 20, showWrapper: false }, options);`
> L:39 `if (settings.showWrapper) {$(element).wrap('<div class="av-container"></div>');}`
> L:63: ` if (settings.showWrapper) { var elementParentContainer = $(element).parent('.av-container'); } else { var elementParentContainer = $(element); }`

Can you help? I m passing same, but i am just begin in this code world. Can you show me how turnout your code, because line numbers are diferent here and i dont no how to fix that.

**Comment by jjcosgrove** [comment]
Thanks for the continued interest @godsdog @suetorres. Sorry for delay, it has been a bit hectic.

@suetorres - I believe the fix would look something **_like_** this (not tested, so do not use without testing yourself!):

https://jsfiddle.net/wjhz3ecv/1/

You can copy the code in the bottom/script window over the aniview.js file you have in your project (be sure to check it into your repo or fork mine, fix it, and then use that in your package.json)

Happy coding!

**Comment by jjcosgrove** [comment]
Closing for now - if this becomes a more requested feature I will re-open and consider implementing enable/disable of container via options
