### ISSUE TITLE
Animations all play on load

### ISSUE THREAD

**Issue by wrnlai** [jjcosgrove/jquery-aniview#19]
Hi! I've been playing around with Aniview and I keep running into the problem of having all my animations play at once. I think I've imported all the necessary components (jQuery, animate.css, aniview.js, initialization script) but my problem still persists. I've attached a link to this https://warrenlai.me/ubiquity-repositories%20av.html

Could this be a problem regarding the note below?

"Any element already in the viewport when the user loads the page will have it's animation triggered immediately if one has been set. In other words, it will not wait for the user to begin scrolling before initiating the animation on these elements."

**Comment by jjcosgrove** [comment]
Site posted by OP no longer exists so unable to replicate. Closing for now as its rather old...

At a guess, its not likely related to the 'items shown in view will animate immediately' unless... your whole site/page was indeed in view at load. Its more likely a misconfiguration or some conflict with another library. Hard to say sadly...
