### ISSUE TITLE
Animations don't work unless using old version of animate.css

### ISSUE THREAD

**Issue by testcodeaccount2** [jjcosgrove/jquery-aniview#21]
I was replicating an example you have (https://github.com/jjcosgrove/jquery-aniview#full-example), and it does not work unless I grab the old version of animate.css you use on your main site (https://jjcosgrove.github.io/jquery-aniview/).

I am able to use the latest versions of jquery and jquery-aniview for that example, but not the latest version of animate.css because it prevents the animation from playing.

I am not sure if this is simply my fault, or if there is a compatibility issue somewhere.

**Comment by jjcosgrove** [comment]
Hi @testcodeaccount2 !

Thanks for using AniView :)

Looking at the animate.css docs it appears there are some breaking changes!

https://animate.style/#migration

Having only glanced at the new version I suspect its the new prefixed classes causing the issue. You should be able to download a local copy of my lib and modify it to include the prefix if you still want to use it

I might try and implement a version flag at some point but may not be for a while...

hint... might be able to make the change here:

https://github.com/jjcosgrove/jquery-aniview/blob/f447361ab19e425fbdeb4bb7d030e968e61fb079/dist/jquery.aniview.js#L64

**Comment by jjcosgrove** [comment]
@testcodeaccount2

you could also try simply adding all new classes
to the data attribute... not tested but *might* work

**UPDATE** I just did a quick fiddle and it seems to work by simply adding all the new classes in the data attribute:

https://jsfiddle.net/s2od1jfc/1/

**Comment by testcodeaccount2** [comment]
Thank you very much. That last suggestion of adding the new classes into the data attribute worked perfectly. 

Now that it's working for me, I've noticed a slight problem in my case. Would you have any advice on getting individual masonry photos to animate individually? I've got lots of masonry photos, but once I scroll down to the first few photos, all of the photos play their animations. This sounds similar to Issue #19.

EDIT: After reading Issue #11, I can see that this scrolling feature probably isn't implemented. If this is the case and if nothing new has been done on this front, feel free to close this thread. My initial problem was solved.
