### ISSUE TITLE
aniview with keyframe that shows opacity: 0

### ISSUE THREAD

**Issue by kmon25** [jjcosgrove/jquery-aniview#22]
There have one problem from my project,
when I use keyframe animation with aniview,
it happens the opacity always is 0
can not over it, even I use !important at my css.
is anyone can give me a suggestion?

*my keyframe have to infinite floating, so that it no suit for the show out.

**Comment by jjcosgrove** [comment]
Not sure I follow 💯 but you can create your custom animation and it should work just fine? Here is an example of a 'floating' image and 'floating' text for e.g...

https://jsfiddle.net/e2uv0bc1/5/
