### ISSUE TITLE
animated update

### ISSUE THREAD

**Issue by valtingojer** [jjcosgrove/jquery-aniview#24]
Hi There
the animated got updated and now it is using an animate__ as class mark,
i did one update in my aniview.js with

added
line2
const animateCalss = "animate__animated";
line 64 (before 63)
$(element).addClass(animateCalss + " " + $(element).attr('data-av-animation'));

now its working nicely

**Comment by GastroGeek** [comment]
@valtingojer I just pushed an update with v4 support via the `animateClass` option.

If you set it to `animate__animated` you can then just add your `animate__jackInTheBox` or whatever and it will work.

Doing it this way, keeps compatability with v3 and potentially allows future compatability (and maybe even some custom stuff for anyone who loves rolling their own css animations).

**Comment by jjcosgrove** [comment]
@valtingojer I just pushed an update with v4 support. If you set the new option `animateClass` to `animate__animated` then you should be able to use the newer v4 classes like `animate__jackInTheBox` etc.

Doing it this way, I hope to maintain compatability with v3, provide v4 support and potentially maintain compatbaility with future versions of animate.css... and maybe even allow those folks who like rolling their own animation classes to use this with it!
