### ISSUE TITLE
create a package for npm

### ISSUE THREAD

**Issue by Mithgol** [jjcosgrove/jquery-aniview#3]
As you may already know, [jQuery Plugins](http://plugins.jquery.com/) repository has gone to “read only” mode and thus the authors of jQuery plugins have been advised to [create packages](http://blog.npmjs.org/post/111475741445/publishing-your-jquery-plugin-to-npm-the-quick) for [npm](https://www.npmjs.com/) out of their plugins.

Consider creating a jQuery AniView package for npm.

**Comment by Mithgol** [comment]
The rationale here is that [Animate.css](https://daneden.github.io/animate.css/) already provides its own [npm package](https://www.npmjs.org/package/animate.css) and thus sooner or later someone would want to declare both Animate.css and jQuery AniView as dependencies of some web application.

**Comment by jjcosgrove** [comment]
@Mithgol 

Thanks to you - I have just published my first npm package which can be found, here:

https://www.npmjs.com/package/jquery-aniview

Thanks for the feedback and I hope it's useful to you!
