### ISSUE TITLE
Code is not running perfectly

### ISSUE THREAD

**Issue by Manisha-Bajaj** [jjcosgrove/jquery-aniview#8]
I have used your provided code and add downloaded jquery.aniview.js and cdn of jquery . But still it is working correctly means not showing jquery effects. 

Can you tell me any solution

**Comment by jjcosgrove** [comment]
Hi,

Can you please provide more information so I can try to help? Either:

* Access to the code - if its on a live/staging site somewhere I can access
* An example/copy of the code you are using.

It should be fairly straight forward to set up?

* Include Animate.css
* Include jQuery
* Include aniview
* Ensure your elements have for e.g:
```
<div class="aniview" data-av-animation="slideInRight"></div>
```
* Then just run the plugin:
```
$('.aniview').AniView();
```

That should be enough. Check your browser 'console' for any errors. Maybe something is firing too late or not being included properly? Let me know how you get on!

Thanks

**Comment by jjcosgrove** [comment]
PS - here is a working 'fiddle' - perhaps that helps?

https://jsfiddle.net/25gv64tv/

**Comment by jjcosgrove** [comment]
@Manisha-Bajaj 

As you have not responded/continued the conversation - I shall assume you have sorted this and will thus close the issue.

Regards
